name: Lighthouse CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.github/workflows/lighthouse.yml'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build demo-docs
        run: |
          cd apps/demo-docs
          pnpm build

      - name: Build sample-docs
        run: |
          cd apps/sample-docs
          pnpm build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI - demo-docs
        run: |
          cd apps/demo-docs
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Run Lighthouse CI - sample-docs
        run: |
          cd apps/sample-docs
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse reports - demo-docs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports-demo-docs
          path: apps/demo-docs/.lighthouseci/
          retention-days: 30

      - name: Upload Lighthouse reports - sample-docs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports-sample-docs
          path: apps/sample-docs/.lighthouseci/
          retention-days: 30
