name: Test and Validate

on:
  push:
    branches: [main]
    paths:
      - 'packages/cli/**'
      - 'packages/validator/**'
      - 'registry/**'
      - 'vitest.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/cli/**'
      - 'packages/validator/**'
      - 'registry/**'
      - 'vitest.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

jobs:
  # CLIパッケージのテスト
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CLI tests
        run: pnpm test:cli

      - name: Upload CLI test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cli-test-results
          path: packages/cli/coverage/
          retention-days: 7

  # Validatorパッケージのテスト
  test-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Validator tests
        run: pnpm test:validator

      - name: Upload Validator test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validator-test-results
          path: packages/validator/coverage/
          retention-days: 7

  # 統合テスト（全パッケージ）
  test-integration:
    runs-on: ubuntu-latest
    needs: [test-cli, test-validator]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run all tests
        run: pnpm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/
          retention-days: 7

  # カバレッジレポート生成
  test-coverage:
    runs-on: ubuntu-latest
    needs: [test-integration]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate coverage report
        run: pnpm test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      # 将来的にCodecovなどのカバレッジサービスに統合可能
      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./coverage/lcov.info

  # レジストリ基本バリデーション
  validate-registry-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate registry (basic mode)
        run: pnpm validate

  # レジストリ厳格モードバリデーション
  validate-registry-strict:
    runs-on: ubuntu-latest
    needs: [validate-registry-basic]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate registry (strict mode)
        run: pnpm validate:strict

  # レジストリ完全バリデーション
  validate-registry-full:
    runs-on: ubuntu-latest
    needs: [validate-registry-strict]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate registry (full mode)
        run: pnpm validate:full
        continue-on-error: true # syncHashの不一致は警告レベル

      - name: Upload validation results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: .backups/
          retention-days: 7

  # プルリクエスト用バリデーションレポート
  validate-pr-report:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [test-integration, validate-registry-strict]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate validation report (JSON)
        run: node scripts/validate-registry.js registry/docs.json --report=json --strict > validation-report.json
        continue-on-error: true

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: pr-validation-report
          path: validation-report.json
          retention-days: 30

      # 将来的にコメントとして投稿可能
      # - name: Comment PR with validation results
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const fs = require('fs');
      #       const report = JSON.parse(fs.readFileSync('validation-report.json', 'utf8'));
      #       // PRにコメントを投稿
